### ISSUE TITLE
Prevent explore.samaritan.works from Being Indexed by Search Engines

### ISSUE THREAD

**Issue by nuthanmunaiah** [samaritan/services#55]
# Description

By default, search engines like Google and Bing will index sites reachable over the Internet. We do not want explore.samaritan.works to be indexed by the search engines at this point because the site is in an _invited preview_ phase. The issue is to track the implementation.

**Comment by JakeD-AVI** [comment]
Review approved - This can be closed (I do not have the ability to do so)
